// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {IERC20} from "forge-std/interfaces/IERC20.sol";
import {Moderation} from "../src/Moderation.sol";
import {ModerationHarness} from "./harnesses/ModerationHarness.sol";
import {MockBZZ} from "./mocks/MockBZZ.sol";
import {StakeRegistry} from "../src/StakeRegistry.sol";
import {IndexRegistry} from "../src/IndexRegistry.sol";
import {StackDeployer} from "./base/StackDeployer.sol";

/// Differential test (work order D10): replays the settlement vectors generated by
/// `simulation/vectors/export_vectors.py` (expected values from the independent
/// Python integer reference `reference_int.settle`) against the real `claim()`,
/// asserting bit-exact agreement on rewards, the committed→free/frozen
/// disposition, appeal refunds+bonuses, and the claim bounty.
contract DifferentialTest is StackDeployer {
    string internal json;
    address internal claimant = makeAddr("claimant");

    ModerationHarness internal mod;
    StakeRegistry internal stakeReg;
    MockBZZ internal bzz;
    /// Vector currently being replayed: scopes participant addresses so one
    /// shared stack can host all 52 vectors (a fresh three-contract deployment
    /// per vector overruns the per-test gas limit). Each vector still starts from
    /// zero balances because its participants are addresses nothing has touched.
    uint256 internal vec;

    function setUp() public {
        json = vm.readFile("test/vectors/settlement_vectors.json");
        bzz = new MockBZZ();
        (mod, stakeReg,) = _deployStack(bzz);
    }

    function _voter(uint256 i) internal returns (address) {
        return makeAddr(string(abi.encodePacked("dv", vec, "_", i)));
    }

    function _contrib(uint256 i) internal returns (address) {
        return makeAddr(string(abi.encodePacked("dc", vec, "_", i)));
    }

    function _u(uint256 i, string memory field) internal view returns (uint256) {
        return vm.parseJsonUint(json, string.concat(".v[", vm.toString(i), "].", field));
    }

    function _ua(uint256 i, string memory field) internal view returns (uint256[] memory) {
        return vm.parseJsonUintArray(json, string.concat(".v[", vm.toString(i), "].", field));
    }

    function _ba(uint256 i, string memory field) internal view returns (bool[] memory) {
        return vm.parseJsonBoolArray(json, string.concat(".v[", vm.toString(i), "].", field));
    }

    function test_settlement_matches_reference_for_all_vectors() public {
        uint256 count = vm.parseJsonUint(json, ".count");
        assertGe(count, 50, "at least 50 vectors");
        for (uint256 i = 0; i < count; i++) {
            _replay(i);
        }
    }

    function _replay(uint256 i) internal {
        vec = i;
        uint256 caseId = mod.__injectFinalized(0, Moderation.Outcome(_u(i, "finalOutcome")), _u(i, "pot"));
        bzz.mint(address(mod), _u(i, "pot"));
        uint256 nRounds = _u(i, "nRounds");
        for (uint256 d = 0; d < nRounds; d++) {
            mod.__injectRound(caseId);
        }

        _injectSeats(i, caseId);
        _injectBonds(i, caseId, nRounds);

        uint256 balBefore = bzz.balanceOf(claimant);
        vm.prank(claimant);
        mod.claim(caseId);
        uint256 gotBounty = bzz.balanceOf(claimant) - balBefore;

        _assertVector(i, gotBounty, caseId);
    }

    function _injectSeats(uint256 i, uint256 caseId) internal {
        uint256[] memory rnd = _ua(i, "seat_round");
        uint256[] memory voter = _ua(i, "seat_voter");
        uint256[] memory seats = _ua(i, "seat_seats");
        uint256[] memory camt = _ua(i, "seat_camt");
        uint256[] memory rc = _ua(i, "seat_rc");
        for (uint256 k = 0; k < voter.length; k++) {
            mod.__injectSeat(caseId, rnd[k], _voter(voter[k]), seats[k], camt[k], uint8(rc[k]));
            if (camt[k] > 0) bzz.mint(address(mod), camt[k]); // back committed stake
        }
    }

    function _injectBonds(uint256 i, uint256 caseId, uint256 nRounds) internal {
        bool[] memory bondInPot = _ba(i, "round_bondInPot");
        uint256[] memory appealFor = _ua(i, "round_appealFor");
        for (uint256 d = 0; d < nRounds; d++) {
            mod.__injectBond(caseId, d, Moderation.Outcome(appealFor[d]), bondInPot[d]);
        }
        uint256[] memory cr = _ua(i, "contrib_round");
        uint256[] memory ci = _ua(i, "contrib_idx");
        uint256[] memory ca = _ua(i, "contrib_amt");
        for (uint256 k = 0; k < ci.length; k++) {
            mod.__injectBondContrib(caseId, cr[k], _contrib(ci[k]), ca[k]);
        }
    }

    function _assertVector(uint256 i, uint256 gotBounty, uint256 caseId) internal {
        assertEq(gotBounty, _u(i, "exp_claimBounty"), _msg(i, "claimBounty"));

        uint256[] memory fIdx = _ua(i, "exp_free_idx");
        uint256[] memory fAmt = _ua(i, "exp_free_amt");
        for (uint256 k = 0; k < fIdx.length; k++) {
            (uint256 free,,,,,,,,) = mod.moderatorInfo(_voter(fIdx[k]));
            assertEq(free, fAmt[k], _msg(i, "free"));
        }
        uint256[] memory zIdx = _ua(i, "exp_frozen_idx");
        uint256[] memory zAmt = _ua(i, "exp_frozen_amt");
        for (uint256 k = 0; k < zIdx.length; k++) {
            (,,, uint256 frozen,,,,,) = mod.moderatorInfo(_voter(zIdx[k]));
            assertEq(frozen, zAmt[k], _msg(i, "frozen"));
        }
        uint256[] memory pIdx = _ua(i, "exp_payout_idx");
        uint256[] memory pAmt = _ua(i, "exp_payout_amt");
        for (uint256 k = 0; k < pIdx.length; k++) {
            // C-01: refunds+bonuses are pulled via claimAppealPayout; the pristine
            // (pre-pull) owed amount equals the reference's exact pro-rata share.
            assertEq(mod.appealPayoutOwed(caseId, _contrib(pIdx[k])), pAmt[k], _msg(i, "payout"));
        }

        uint256 buckets = mod.totalFreeStake() + mod.totalCommittedStake() + mod.totalFrozenStake();
        assertEq(
            bzz.balanceOf(address(mod)),
            buckets + mod.openPotsTotal() + mod.totalPendingBond() + mod.totalPendingPayout(),
            _msg(i, "conservation")
        );
    }

    function _msg(uint256 i, string memory what) internal pure returns (string memory) {
        return string.concat("vector ", vm.toString(i), ": ", what, " mismatch");
    }
}
